/** Server-safe country lookup for geocoding (no client-only deps). */
export const GEO_COUNTRIES: Record<
    string,
    { name: string; viewbox?: string }
> = {
    zm: { name: 'Zambia', viewbox: '21.999,-8.224,33.706,-18.079' },
    zw: { name: 'Zimbabwe', viewbox: '25.237,-15.609,33.056,-22.417' },
    mw: { name: 'Malawi', viewbox: '32.67,-9.36,35.92,-17.13' },
    mz: { name: 'Mozambique' },
    bw: { name: 'Botswana' },
    na: { name: 'Namibia' },
    ao: { name: 'Angola' },
    cd: { name: 'DR Congo' },
    cg: { name: 'Congo' },
    ke: { name: 'Kenya', viewbox: '33.9,5.0,41.9,-4.7' },
    ug: { name: 'Uganda' },
    tz: { name: 'Tanzania' },
    rw: { name: 'Rwanda' },
    bi: { name: 'Burundi' },
    ng: { name: 'Nigeria' },
    gh: { name: 'Ghana' },
    ci: { name: "Côte d'Ivoire" },
    sn: { name: 'Senegal' },
    et: { name: 'Ethiopia' },
    za: { name: 'South Africa' },
    eg: { name: 'Egypt' },
    ma: { name: 'Morocco' },
    fi: { name: 'Finland' },
    se: { name: 'Sweden' },
    no: { name: 'Norway' },
    dk: { name: 'Denmark' },
    ee: { name: 'Estonia' },
    lv: { name: 'Latvia' },
    lt: { name: 'Lithuania' },
    de: { name: 'Germany' },
    fr: { name: 'France' },
    gb: { name: 'United Kingdom' },
    ie: { name: 'Ireland' },
    nl: { name: 'Netherlands' },
    be: { name: 'Belgium' },
    es: { name: 'Spain' },
    pt: { name: 'Portugal' },
    it: { name: 'Italy' },
    ch: { name: 'Switzerland' },
    at: { name: 'Austria' },
    pl: { name: 'Poland' },
    cz: { name: 'Czechia' },
    ae: { name: 'United Arab Emirates' },
    sa: { name: 'Saudi Arabia' },
    qa: { name: 'Qatar' },
    us: { name: 'United States' },
    ca: { name: 'Canada' },
    mx: { name: 'Mexico' },
    br: { name: 'Brazil' },
    ar: { name: 'Argentina' },
    in: { name: 'India' },
    sg: { name: 'Singapore' },
    my: { name: 'Malaysia' },
    id: { name: 'Indonesia' },
    ph: { name: 'Philippines' },
    th: { name: 'Thailand' },
    vn: { name: 'Vietnam' },
    jp: { name: 'Japan' },
    kr: { name: 'South Korea' },
    au: { name: 'Australia' },
    nz: { name: 'New Zealand' },
};
